[package]
name = "lending_controller"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
soroban-sdk = { workspace = true }

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }
ed25519-dalek = { version = "3", features = ["rand_core"] }
wrapped_asset = { path = "../../treasury/soroban" }
lending_pool = { path = "../../lending/soroban" }
collateral_vault = { path = "../../collateral/soroban" }
oracle = { path = "../../oracle/soroban" }
